// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
)

type Box struct {
	ID     int32 `json:"id"`
	MailID int32 `json:"mail_id"`
	Owner  int32 `json:"owner"`
	Sender int32 `json:"sender"`
}

type Mail struct {
	ID        int32        `json:"id"`
	Title     string       `json:"title"`
	Body      string       `json:"body"`
	Receiver  int32        `json:"receiver"`
	Sender    int32        `json:"sender"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	CreatedAt sql.NullTime `json:"created_at"`
}
